### ISSUE TITLE
Add config

### ISSUE THREAD

**Issue by dabulashvili-zz** [eugeny-dementev/winston-console-formatter#1]
Can you add configs to present meta and stack.
Like that: 

```
logger.add(winston.transports.Console, toYAML.config({
    metaLevel: 'warning', // or printMeta: true
    stackLevel: 'error' // or printStack: true
}));
```

I think it will be more usefull.

**Comment by eugeny-dementev** [comment]
@DatoBula, thank you, good idea. metaLevel/stackLevel looks really useful. You can rewrite your PR to this type options and i merge it. With tests please.
Or i can do it by myself, but next week.

**Comment by dabulashvili-zz** [comment]
OK, I'll try to change options and create new PR.

**Comment by eugeny-dementev** [comment]
Added in `1.0.0-beta.0`
```js
{
  stackTrace: Boolean,
  meta: Boolean,
}
```
